agent_server:
  host: 0.0.0.0
  port: 8003
  web_concurrency: 1

agent:
  external_url: http://${HOSTNAME}:8003

data_extraction:
  year: "2023"
  url: "https://www.data.gouv.fr/en/datasets/bases-de-donnees-annuelles-des-accidents-corporels-de-la-circulation-routiere-annees-de-2005-a-2023/"

evidently:
  base_url: "http://evidently-api:8001"
  public_url: "https://mlops.marcolopes.fr/evidently"

mlflow:
  enabled: true
  tracking_uri: "https://dagshub.com/mclpfr/mlops-road-accidents.mlflow"
  model_name: "accident-severity-predictor"
  username: "franciscdata"
  password: "de2de5faad01289556c22675be4580843d7216e6" 

model:
  type: "RandomForestClassifier"
  random_state: 42
  test_size: 0.2
  cv_folds: 3

postgresql:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "road_accidents"

auth_api:
  base_url: "http://auth_api_service:7999"
  username: "johndoe"
  password: "johnsecret"
  jwt_secret_key: "a-super-secret-key-that-should-be-changed"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 30

predict_api:
  base_url: "http://predict_api_service:8000"


dagshub:
  user: "franciscdata"
  token: "de2de5faad01289556c22675be4580843d7216e6"

dvc:
  dagshub_user: "mclpfr"
  dagshub_token: "46fb4962402bf1118d644028129e9c98e5f60ce6" 

grafana:
  root_url: "https://mlops.marcolopes.fr/grafana"
  domain: "mlops.marcolopes.fr"
  admin_user: "admin"
  admin_password: "Gr4f@n@_Adm1n_2025!"

airflow:
  admin_user: "admin"
  admin_password: "A1rfl0w_Admin_2025#"
  public_url: "https://mlops.marcolopes.fr/airflow"
  fernet_key: 46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=


  core:
    executor: LocalExecutor
    load_examples: False
    dags_are_paused_at_creation: False
    parallelism: 8
    dag_concurrency: 8

  database:
    sql_alchemy_conn: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow

  webserver:
    expose_config: True
    rbac: False
    authenticate: True
    workers: 2
    base_url: /airflow
    enable_proxy_fix: True
    secret_key: 3a9e7d6b2a1f0c9d8e7f6a5b4c3d2e1f0b9a8c7d6e5f4a3b2c1d0e9f8e7f6a5b4

  api:
    auth_backends: airflow.api.auth.backend.basic_auth

  scheduler:
    killed_task_cleanup_time: 60
    scheduler_heartbeat_sec: 5

git:
  user:
    name: "Marco LOPES"
    email: "marco@datascientest.com"

agent:
  log_level: "INFO"
  agent_events_path: "/agent_events/agent_events.jsonl"
  external_url: "https://mlops.marcolopes.fr/agent/"
  max_restarts: 10
  llm_api_key: "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"
  model: "openai/gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

log_retention_days: 5

infrastructure:
  base_url: "mlops.marcolopes.fr"
