agent_server:
  host: 0.0.0.0
  port: 8003
  web_concurrency: 1

agent:
  external_url: http://${HOSTNAME}:8003

data_extraction:
  year: "2023"
  url: "https://www.data.gouv.fr/en/datasets/bases-de-donnees-annuelles-des-accidents-corporels-de-la-circulation-routiere-annees-de-2005-a-2023/"

evidently:
  base_url: "http://evidently-api:8001"
  public_url: "https://vmi2734167.contaboserver.net/evidently"

mlflow:
  enabled: true
  tracking_uri: "https://dagshub.com/mclpfr/mlops-road-accidents.mlflow"
  model_name: "accident-severity-predictor"
  username: "franciscdata"
  password: "de2de5faad01289556c22675be4580843d7216e6" 

model:
  type: "RandomForestClassifier"
  random_state: 42
  test_size: 0.2
  cv_folds: 3

postgresql:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "road_accidents"

auth_api:
  jwt_secret_key: "a-super-secret-key-that-should-be-changed"
  jwt_algorithm: "HS256"
  access_token_expire_minutes: 30


dagshub:
  user: "franciscdata"
  token: "de2de5faad01289556c22675be4580843d7216e6"

dvc:
  dagshub_user: "mclpfr"
  dagshub_token: "46fb4962402bf1118d644028129e9c98e5f60ce6" 

grafana:
  root_url: "https://vmi2734167.contaboserver.net/grafana"
  domain: "vmi2734167.contaboserver.net"
  admin_user: "admin"
  admin_password: "Gr4f@n@_Adm1n_2025!"

airflow:
  admin_user: "admin"
  admin_password: "A1rfl0w_Admin_2025#"
  public_url: "https://vmi2734167.contaboserver.net/airflow"

git:
  user:
    name: "Marco LOPES"
    email: "marco@datascientest.com"

agent:
  log_level: "INFO"
  agent_events_path: "/agent_events/agent_events.jsonl"
  external_url: "https://vmi2734167.contaboserver.net/agent/"
  max_restarts: 10
  llm_api_key: "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"
  model: "openai/gpt-3.5-turbo"
  temperature: 0.7
  max_tokens: 1000

infrastructure:
  base_url: "vmi2734167.contaboserver.net"
