data_extraction:
  year: "2023"
  url: "https://www.data.gouv.fr/en/datasets/bases-de-donnees-annuelles-des-accidents-corporels-de-la-circulation-routiere-annees-de-2005-a-2023/"

mlflow:
  tracking_uri: "https://dagshub.com/mclpfr/mlops-road-accidents.mlflow"
  username: "franciscdata"
  password: "de2de5faad01289556c22675be4580843d7216e6" 

postgresql:
  host: "postgres"
  port: "5432"
  user: "postgres"
  password: "postgres"
  database: "road_accidents" 

dagshub:
  user: "franciscdata"
  token: "de2de5faad01289556c22675be4580843d7216e6"
