version: '3.8'

services:
  extract_data:
    build:
      context: .
      dockerfile: src/extract_data/Dockerfile
    container_name: extract_data_service
    command: python extract_data.py
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app

  prepare_data:
    build:
      context: .
      dockerfile: src/prepare_data/Dockerfile
    container_name: prepare_data_service
    command: sh -c "while [ ! -f /app/data/raw/accidents_2023.csv ]; do sleep 1; done; python prepare_data.py"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    depends_on:
      - extract_data

  train_model:
    build:
      context: .
      dockerfile: src/train_model/Dockerfile
    container_name: train_model_service
    command: sh -c "while [ ! -f /app/data/processed/prepared_accidents_2023.csv ]; do sleep 1; done; python train_model.py"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    depends_on:
      - prepare_data
