version: '3.8'

services:
  extract_data:
    build:
      context: .
      dockerfile: src/extract_data/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: extract_data_service
    command: python extract_data.py
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app

  prepare_data:
    build:
      context: .
      dockerfile: src/prepare_data/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: prepare_data_service
    command: sh -c "while [ ! -f /app/data/raw/accidents_2023.csv ]; do sleep 1; done; python prepare_data.py"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    depends_on:
      - extract_data

  train_model:
    build:
      context: .
      dockerfile: src/train_model/Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: train_model_service
    command: sh -c "while [ ! -f /app/data/processed/prepared_accidents_2023.csv ]; do sleep 1; done; python train_model.py"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    depends_on:
      - prepare_data

  postgres:
    build:
      context: .
      dockerfile: src/postgresql/Dockerfile
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/postgresql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  data_import:
    build:
      context: .
      dockerfile: src/data_import/Dockerfile
    container_name: data_import_service
    command: sh -c "/app/wait-for-postgres.sh postgres 5432 python3 /app/import_data.py"
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
      - ./models:/app/models
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: road_accidents
    depends_on:
      postgres:
        condition: service_healthy
      train_model:
        condition: service_started

  auto_dvc:
    build:
      context: .
      dockerfile: src/auto_dvc/Dockerfile
    container_name: auto_dvc_service
    command: sh -c "while [ ! -f /app/models/rf_model_2023.joblib ]; do sleep 2; done; python auto_dvc.py"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./.dvc:/app/.dvc
      - ./.dvcignore:/app/.dvcignore
      - ./dvc.yaml:/app/dvc.yaml
      - ./dvc.lock:/app/dvc.lock
      - ./config.yaml:/app/config.yaml
      - ./src:/app/src
      - ./.git:/app/.git
    working_dir: /app
    depends_on:
      - extract_data
      - prepare_data
      - train_model
      - postgres
      - data_import

volumes:
  postgres_data:
