x-user-info: &user-info
  USER_ID: "1000"
  GROUP_ID: "1000"

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow/Dockerfile
    args:
      <<: *user-info
  user: "0"
  environment:
    - AIRFLOW__CORE__EXECUTOR=LocalExecutor

    - AIRFLOW_ADMIN_PASSWORD=admin
    - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
    - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
    - AIRFLOW__CORE__LOAD_EXAMPLES=False
    - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=False
    - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
    - AIRFLOW__WEBSERVER__RBAC=False
    - AIRFLOW__WEBSERVER__AUTHENTICATE=True
    - AIRFLOW__WEBSERVER__SECRET_KEY=mydummysecret123
    - AIRFLOW_HOME=/opt/airflow
    - AIRFLOW__API__AUTH_BACKENDS=airflow.api.auth.backend.basic_auth
    - AIRFLOW__CORE__PARALLELISM=8
    - AIRFLOW__CORE__DAG_CONCURRENCY=8
    - AIRFLOW__WEBSERVER__WORKERS=2
    - AIRFLOW__SCHEDULER__MAX_THREADS=2
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/plugins:/opt/airflow/plugins
    - /var/run/docker.sock:/var/run/docker.sock
    - airflow_logs:/opt/airflow/logs
    - ./.:/opt/project

  deploy:
    resources:
      limits:
        cpus: '2.0'
        memory: 4G
      reservations:
        cpus: '0.5'
        memory: 1G
  depends_on:
    postgres-airflow:
      condition: service_healthy

x-airflow-common-env: &airflow-common-env {}

services:
  extract_data:
    build:
      context: .
      dockerfile: src/extract_data/Dockerfile
      args:
        <<: *user-info
    container_name: extract_data_service
    command: python extract_data.py
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  synthet_data:
    build:
      context: .
      dockerfile: src/synthet_data/Dockerfile
      args:
        <<: *user-info
    container_name: synthet_data_service
    command: python synthet_data.py
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      - extract_data

  prepare_data:
    build:
      context: .
      dockerfile: src/prepare_data/Dockerfile
      args:
        <<: *user-info
    container_name: prepare_data_service
    command: python prepare_data.py
    volumes:
      - ./data:/app/data
      - ./config.yaml:/app/config.yaml
      - ./models:/app/models
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    depends_on:
      - synthet_data
      
  import_data:
    build:
      context: .
      dockerfile: src/import_data/Dockerfile
      args:
        <<: *user-info
    container_name: import_data_service
    command: >
      sh -c "/app/wait-for-postgres.sh postgres 5432 && python import_data.py"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./config.yaml:/app/config.yaml
      - ./src/import_data/wait-for-postgres.sh:/app/wait-for-postgres.sh
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      postgres:
        condition: service_healthy

  train_model:
    build:
      context: .
      dockerfile: src/train_model/Dockerfile
      args:
        <<: *user-info
    container_name: train_model_service
    user: root
    command: >
      sh -c "
        chown -R appuser:appuser /app/models;
        rm -f /app/models/train_model.done;
        su -c 'python train_model.py' appuser
      "
    volumes:
      - ./data:/app/data:rw
      - ./models:/app/models:rw
      - ./config.yaml:/app/config.yaml:rw
      - ./.git:/app/.git:rw
      - ./dvc.yaml:/app/dvc.yaml:rw
      - ./.dvc:/app/.dvc:rw
      - ./src/prepare_data:/app/src/prepare_data:ro
      - ./src/synthet_data:/app/src/synthet_data:ro
    working_dir: /app
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 3G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      - prepare_data
      - synthet_data

  postgres:
    build:
      context: .
      dockerfile: src/postgresql/Dockerfile
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: road_accidents
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/postgresql/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.3'
          memory: 512M

  auth_api:
    container_name: auth_api_service
    build:
      context: .
      dockerfile: src/auth_api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    ports:
      - "7999:7999"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "api"
        labels: "logging"
        env: "logging_job"
    labels:
      - "logging=promtail"
      - "logging_job=api"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    depends_on:
      - train_model

  predict_api:
    container_name: predict_api_service
    build:
      context: .
      dockerfile: src/predict_api/Dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
      - LOG_FORMAT=json
    volumes:
      - ./models:/app/models
      - ./data:/app/data
    ports:
      - "8000:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "api"
        labels: "logging"
        env: "logging_job"
    labels:
      - "logging=promtail"
      - "logging_job=api"
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    depends_on:
      - auth_api

  streamlit:
    container_name: streamlit
    build:
      context: .
      dockerfile: streamlit/app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - AIRFLOW_BASE_URL=http://localhost:8080
      - GRAFANA_BASE_URL=http://localhost:3000
      - EVIDENTLY_BASE_URL=http://evidently-api:8001
    volumes:
      - ./:/app
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    depends_on:
      - airflow-webserver
      - grafana
      - evidently-api

  agent:
    container_name: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=INFO
    volumes:
      - ./agent:/app
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 128M

  evidently-api:                       
    container_name: evidently-api
    build:                                                
      context: ./evidently/api        
      dockerfile: Dockerfile
      args:  
        <<: *user-info
    user: "root"
    volumes:                 
      - ./evidently/api:/app
      - ./evidently/ui:/app/ui/target
      - ./evidently/reference:/app/reference     
      - ./evidently/current:/app/current     
    ports:
      - "8001:8001"
    environment:   
      - EVIDENTLY_PROJECT_NAME=Road Accidents MLOps
      - EVIDENTLY_PROJECT_DESCRIPTION=Monitoring dashboard for road accident prediction model
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    networks:
      - default

  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: prometheus_service
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/  
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M
    depends_on:
      - predict_api
      - evidently-api
      - alertmanager
    networks:
      - default

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager_service
    ports:
      - '9093:9093'
    volumes:
      - ./monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    networks:
      - default

  loki:
    image: grafana/loki:2.9.0
    container_name: loki_service
    ports:
      - "3100:3100"
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./monitoring/loki/local-config.yaml:/etc/loki/local-config.yaml
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 256M

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail_service
    restart: unless-stopped
    user: root
    privileged: true
    security_opt:
      - apparmor:unconfined
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log:/var/log:ro
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/lib/docker:/var/lib/docker:ro
    command:
      - "-config.file=/etc/promtail/config.yaml"
      - "-config.expand-env=true"
    environment:
      - HOSTNAME=${HOSTNAME}
      - HOST_IP=${HOST_IP}
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_service
    restart: always
    ports:
      - 3000:3000
    networks:
      - default
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=lax
      - GF_SECURITY_X_FRAME_OPTIONS=allow-from-all
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/provisioning/dashboards/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./monitoring/grafana/provisioning/dashboards/json:/etc/grafana/provisioning/dashboards/json
      - grafana_data:/var/lib/grafana
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.2'
          memory: 256M
    depends_on:
      - prometheus
      - alertmanager
      - postgres
      - loki

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    container_name: cadvisor_service
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M

  postgres-airflow:
    image: postgres:13
    container_name: postgres-airflow
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5433:5432"
    volumes:
      - postgres_airflow_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.3'
          memory: 512M
      
  airflow-init:
    <<: *airflow-common
    user: "0"
    container_name: airflow-init
    restart: on-failure
    healthcheck:
      test: ["CMD", "airflow", "db", "check-migrations"]
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 512M
    depends_on:
      postgres-airflow:
        condition: service_healthy

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 20s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      postgres-airflow:
        condition: service_healthy

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    restart: always
    healthcheck:
      test: ["CMD", "airflow", "jobs", "check", "--job-type", "SchedulerJob", "--hostname", "$${HOSTNAME}"]
      interval: 30s
      timeout: 30s
      retries: 10
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      postgres-airflow:
        condition: service_healthy
      airflow-webserver:
        condition: service_healthy
    environment:
      <<: *airflow-common-env
      AIRFLOW_ADMIN_PASSWORD: admin
      AIRFLOW__CORE__KILLED_TASK_CLEANUP_TIME: 60
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres-airflow:5432/airflow
      AIRFLOW__CORE__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: 5

  drift-controller:
    build:
      context: ./drift-controller
      dockerfile: Dockerfile
    container_name: drift_controller_service
    ports:
      - "8002:8000"
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
      - AIRFLOW_URL=http://airflow-webserver:8080/api/v1/dags/road_accidents/dagRuns
      - AIRFLOW_USER=airflow
      - AIRFLOW_PASSWORD=airflow
      - DRIFT_THRESHOLD=0.5
      - CHECK_INTERVAL_SECONDS=10
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
    depends_on:
      - prometheus
      - airflow-webserver
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
  alertmanager_data:
  postgres_airflow_data:
  airflow_logs:
