apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict "https://index.docker.io/v1/" (dict "username" .Values.dockerhub.username "password" .Values.dockerhub.token "auth" (printf "%s:%s" .Values.dockerhub.username .Values.dockerhub.token | b64enc))) | toJson | b64enc }} 