{
 "title": "Best Model Metrics",
 "tags": [
  "model",
  "metrics"
 ],
 "refresh": "5s",
 "panels": [
  {
   "title": "Model Version",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, model_version as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "x": 3, "y": 0, "w": 3, "h": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, year as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, accuracy as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Precision (Macro Avg)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, precision_macro_avg as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "Recall (Macro Avg)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 4, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, recall_macro_avg as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  },
  {
   "title": "F1 Score (Macro Avg)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT run_date as time, f1_macro_avg as value FROM best_model_metrics ORDER BY accuracy DESC LIMIT 1;"
    }
   ]
  }
 ]
}