global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'airflow_webhook'
  routes:
    - match:
        alertname: HighDataDrift
      receiver: 'airflow_webhook'
      repeat_interval: 1h  

receivers:
- name: 'airflow_webhook'
  webhook_configs:
  - url: 'http://172.18.0.5:8001/trigger_airflow_from_alert'
    send_resolved: false  
    http_config:
      basic_auth:
        username: 'airflow'
        password: 'airflow'
    max_alerts: 3
