global:
  # Réduit le temps avant qu'une alerte soit marquée comme résolue
  resolve_timeout: 1m

route:
  group_by: ['alertname', 'severity']
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  # Route toutes les alertes vers un récepteur qui ne fait rien.
  receiver: 'null'
  routes:
    - receiver: 'null'
      continue: false

receivers:
  - name: 'null'
