global:
  scrape_interval: 15s  
  evaluation_interval: 15s  

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api'
    static_configs:
      - targets: ['api_service:8000']  

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor_service:8080']

  - job_name: 'evidently_drift_api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['evidently-api:8001']
    scheme: http
    scrape_interval: 15s
    scrape_timeout: 10s
