apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: postgres:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: road_accidents
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      postgresVersion: 1000
      timescaledb: false

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus_service:9090
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      maxLines: 1000
    uid: 'Loki'