{
 "title": "Best Model Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT model_version::text as metric, model_version as value FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Year",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT year::text as metric, year as value FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Accuracy",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT accuracy FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Precision",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT precision_macro_avg FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "Recall",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT recall_macro_avg FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "F1 Score",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT f1_macro_avg FROM best_model_metrics ORDER BY run_date DESC LIMIT 1"
    }
   ]
  }
 ]
}