name: Test of the ML Pipeline for Road Accidents

on:
  push:  
    branches:
      - main
  pull_request:  
    branches:
      - main
  workflow_dispatch:  

jobs:
  test-pipeline:
    name: Test Pipeline
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: accidents
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Recreate config.yaml from secret
        run: |
          echo "${{ secrets.CONFIG_YAML }}" > config.yaml

      - name: Create necessary directories
        run: |
          mkdir -p data models
          chmod 777 models  

      - name: Build and run extract_data container
        run: |
          docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t extract_data_service -f src/extract_data/Dockerfile .
          docker run --rm -v $(pwd)/data:/app/data -v $(pwd)/config.yaml:/app/config.yaml extract_data_service
          if [ -f "data/raw/accidents_2023.csv" ]; then
            touch data/raw/extract_data.done
            echo "Created marker file: data/raw/extract_data.done"
          else
            echo "Error: Data file not created"
            exit 1
          fi

      - name: Build and run synthet_data container
        run: |
          docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t synthet_data_service -f src/synthet_data/Dockerfile .
          docker run --rm -v $(pwd)/data:/app/data -v $(pwd)/config.yaml:/app/config.yaml synthet_data_service
          if [ -f "data/raw/accidents_2023_synthet.csv" ]; then
            touch data/raw/accidents_2023_synthet.done
            echo "Created marker file: data/raw/accidents_2023_synthet.done"
          else
            echo "Error: Synthet data file not created"
            exit 1
          fi

      - name: Build and run prepare_data container
        run: |
          docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t prepare_data_service -f src/prepare_data/Dockerfile .
          docker run --rm -v $(pwd)/data:/app/data -v $(pwd)/models:/app/models -v $(pwd)/config.yaml:/app/config.yaml prepare_data_service
          if [ -f "data/processed/prepared_accidents_2023.csv" ]; then
            touch data/processed/prepared_data.done
            echo "Created marker file: data/processed/prepared_data.done"
          else
            echo "Error: Prepared data file not created"
            exit 1
          fi

      - name: Build and run train_model container
        env:
          MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t train_model_service -f src/train_model/Dockerfile .
          docker run --rm \
            -v $(pwd)/data:/app/data \
            -v $(pwd)/models:/app/models \
            -v $(pwd)/config.yaml:/app/config.yaml \
            -e MLFLOW_TRACKING_URI="${MLFLOW_TRACKING_URI}" \
            -e MLFLOW_TRACKING_USERNAME="${MLFLOW_TRACKING_USERNAME}" \
            -e MLFLOW_TRACKING_PASSWORD="${MLFLOW_TRACKING_PASSWORD}" \
            train_model_service
          if [ -f "models/train_model.done" ]; then
            echo "Training completed successfully"
          else
            echo "Error: Training did not complete successfully"
            exit 1
          fi

      - name: Build API Docker image
        run: docker build --build-arg USER_ID=$(id -u) --build-arg GROUP_ID=$(id -g) -t api_service -f src/api/Dockerfile .

      - name: Run API container
        run: |
          docker run -d --name api_service -p 8000:8000 \
            -v $(pwd)/models:/app/models \
            -v $(pwd)/data:/app/data \
            api_service

      - name: Wait for API to be ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/docs; then
              echo "API is up!"
              break
            fi
            echo "Waiting for API..."
            sleep 2
          done

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        working-directory: .
        run: |
          pytest tests/ -v

      - name: Build and push extract_data image
        if: success()
        run: |
          docker tag extract_data_service ${{ secrets.DOCKER_USERNAME }}/extract_data_service:${{ github.run_number }}
          docker tag extract_data_service ${{ secrets.DOCKER_USERNAME }}/extract_data_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/extract_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/extract_data_service:latest

      - name: Build and push synthet_data image
        if: success()
        run: |
          docker tag synthet_data_service ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:${{ github.run_number }}
          docker tag synthet_data_service ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:latest

      - name: Build and push prepare_data image
        if: success()
        run: |
          docker tag prepare_data_service ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:${{ github.run_number }}
          docker tag prepare_data_service ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:latest

      - name: Build and push train_model image
        if: success()
        run: |
          docker tag train_model_service ${{ secrets.DOCKER_USERNAME }}/train_model_service:${{ github.run_number }}
          docker tag train_model_service ${{ secrets.DOCKER_USERNAME }}/train_model_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/train_model_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/train_model_service:latest

      - name: Build and push postgres image
        if: success()
        run: |
          docker build -t postgres_service -f src/postgresql/Dockerfile .
          docker tag postgres_service ${{ secrets.DOCKER_USERNAME }}/postgres_service:${{ github.run_number }}
          docker tag postgres_service ${{ secrets.DOCKER_USERNAME }}/postgres_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres_service:latest

      - name: Build and push import_data image
        if: success()
        run: |
          docker build -t import_data_service -f src/import_data/Dockerfile .
          docker tag import_data_service ${{ secrets.DOCKER_USERNAME }}/import_data_service:${{ github.run_number }}
          docker tag import_data_service ${{ secrets.DOCKER_USERNAME }}/import_data_service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/import_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/import_data_service:latest
