name: Test of the ML Pipeline for Road Accidents

on:
  push:  
    branches:
      - main
  pull_request:  
    branches:
      - main
  workflow_dispatch:  

jobs:
  test-pipeline:
    name: Test Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Recreate config.yaml from secret
        run: |
          echo "${{ secrets.CONFIG_YAML }}" > config.yaml

      - name: Run extract_data.py
        run: |
          python src/extract_data/extract_data.py

      - name: Run synthet_data.py
        run: |
          python src/synthet_data/synthet_data.py

      - name: Run prepare_data.py
        run: |
          python src/prepare_data/prepare_data.py

      - name: Run train_model.py
        run: |
          python src/train_model/train_model.py

      - name: Run tests.py
        working-directory: .
        run:  pytest tests/ -v

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push extract_data image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/extract_data_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/extract_data_service:latest -f src/extract_data/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/extract_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/extract_data_service:latest

      - name: Build and push synthet_data image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:latest -f src/synthet_data/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/synthet_data_service:latest

      - name: Build and push prepare_data image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:latest -f src/prepare_data/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/prepare_data_service:latest

      - name: Build and push train_model image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/train_model_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/train_model_service:latest -f src/train_model/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/train_model_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/train_model_service:latest

      - name: Build and push postgres image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/postgres_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/postgres_service:latest -f src/postgresql/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/postgres_service:latest

      - name: Build and push import_data image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/import_data_service:${{ github.run_number }} -t ${{ secrets.DOCKER_USERNAME }}/import_data_service:latest -f src/import_data/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/import_data_service:${{ github.run_number }}
          docker push ${{ secrets.DOCKER_USERNAME }}/import_data_service:latest
